name: Allure Reports with history


# on every push every branch except gh-pages
on:
  #schedule:
  #  - cron: '*/5 * * * *' # every 5 minutes
  push:
    branches-ignore:
      - 'gh-pages' # ignore gh-pages
#    paths:
#      - '!.gitlab-ci.yml'
#      - '!allure-template.yml'
#      - '**/allure-history.yml'
#      - 'allure-report-action/*'


jobs:
  autotests:
    name: Upload allure results to Allure EE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Test
        if: always()
        run: yarn test
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        #uses: ./allure-report-action
        if: always()
        #id: allure-report
        with:
          allure_results: playwright-report
          allure_history: allure-history/allure-history
          keep_reports: 10

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history/allure-history
